services:
  ui:
    image: ${UI_IMAGE}
    container_name: ${PROJECT_NAME:-scroll-down-sports-ui}
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_USE_MOCK_ADAPTERS: ${VITE_USE_MOCK_ADAPTERS:-false}
      VITE_APP_VERSION: ${VITE_APP_VERSION:-dev}
    ports:
      - '8080:80'
